### ISSUE TITLE
Encoding missing in django-couchdb-utils/__init__.py

### ISSUE THREAD

**Issue by valberg** [stefankoegl/django-couchdb-utils#4]
When cloning the git repository and trying to use it in a django project i get the following error:

```
SyntaxError: Non-ASCII character '\xc3' in file <site-packages-path>/django_couchdb_utils/__init__.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

This is because of Stefan's last name Kögl.

Adding:

```
#encoding: utf-8
```

in the top of **init**.py fixes the error.

**Comment by stefankoegl** [comment]
fixed in ba6e4a05518a93763abb1372ba29452d4de0791a
