### ISSUE TITLE
bundle crash with django1.4

### ISSUE THREAD

**Issue by cckrause** [stefankoegl/django-couchdb-utils#5]
The first issue i found with django 1.4 was in the used function "get_hexdigits" in the User Document, it was dropped in the current stable release (wtf??)...

discussed on stackoverflow also: http://stackoverflow.com/questions/9324290/importerror-cannot-import-name-get-hexdigest

I already fixed that by using the new functionality "make_password" from the hasher module

from django.contrib.auth.hashers import make_password, check_password, UNUSABLE_PASSWORD.

I fixed this issue... if wanted i will upload my changeset and trigger the pull request.

cheers!

**Comment by cckrause** [comment]
the function name was "get_hexdigest" not "get_hexdigits" .. sorry for that.

**Comment by stefankoegl** [comment]
> I fixed this issue... if wanted i will upload my changeset and trigger the pull request.

Yes, that would be very much appreciated. If you can come up with a backwards-compatible version that would be even better.

Thanks in advance!

**Comment by cckrause** [comment]
Ok checkout my changeset!

Greetz

**Comment by stefankoegl** [comment]
merged, thanks!
